Repository Concert-Mate/Music-Service, pull requests merged in 2024-04, with the labels that each got.

#3 Пофиксил так, что теперь всё сможет запуститься по readme без каких-то лишних действий
  poetry.lock
  pyproject.toml
  readme.md
Labels: bug

#5 Добавил контейнер с редисом, для кэширования запросов к API
  .gitignore
  docker-compose.yml
  main.py
  poetry.lock
  pyproject.toml
  readme.md
  settings.py
Labels: enhancement

#8 Изменил формат ответа, добавил возможность работы без кэширования и порефакторил код
  main.py
  model/__init__.py
  model/track_list.py
  poetry.lock
  pyproject.toml
  response/__init__.py
  response/concerts_response.py
  response/response_code.py
  response/response_status.py
  response/track_list_response.py
  services/__init__.py
  services/yandex_music_service.py
Labels: enhancement

#11 Improved readme
  readme.md
Labels: documentation
